
version: 2

models:
  - name: patients_clean
    columns:
      - name: GENDER
      - name: AGE
      - name: HYPERTENSION
      - name: HEART_DISEASE
      - name: SMOKING_HISTORY
      - name: BMI
      - name: HBA1C_LEVEL
      - name: BLOOD_GLUCOSE_LEVEL
      - name: DIABETES